# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coding Marvels
email: Coming soon...
description: >- # this means to ignore newlines until "baseurl:"
  Coding marvels is my personal blog and I will be focusing on WebAssembly and mostly Blazor! Have you heard of Blazor? No? Yes? Doesn’t matter if the answer is yes or no. We’re gonna have a lot of fun together and we will figure out exciting stuff as we go along, which will help this blog to evolve and give values to others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://codingmarvels.com
twitter_username: Maybe!
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
 
emptyArray: []

comments:
  receiver: # https://{{codingmarvels.com}}/api/PostComment}}
    
  defaults:
  -
  scope:
      path: ''
      type: pages
    values:
      layout: page
      author: saeedG
      commenting: open
  -
  scope:
      path: '_posts'
      type: posts
  values:
      layout: post
      author: saeedG
      commenting: open
  -
  authors:
    saeedG:
        name: Saeed Ghanavat
        email:
        url: https://codingmarvels.com
        
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
