# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coding Marvels
email: codingmarvels@ghanavat.co.uk
show_description: false
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://codingmarvels.com" # the base hostname & protocol for your site, e.g. https://codingmarvels.com
#footerEmailTitle: "Contact me:"
#twitter_username: Maybe!
github_username:  ghanavat
google_analytics: UA-135613674-1

#Social settings
social:
  name: Saeed Ghanavat
  links:
     - https://www.linkedin.com/in/saeed-ghanavat-0a11353b/
github:
  is_project_page: false
  owner_url: https://github.com/ghanavat
  owner_name: Saeed Ghanavat

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

#Header and other pages
header_pages:
  - title: About
    url: /about/
  - title: Contact me
    url: /contactMe/

#Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Post settings
show_excerpts: true
newPostTemporaryPlaceHolder: "Being written..."

# Jekyll comment settings
comments:
  enabled: true
  show_count: true
  receiver: https://codingmarvelscommenting.azurewebsites.net/api/PostComment
  
emptyArray: []

defaults: 
 -
   scope:
    path: ''
    type: pages
   values:
    layout: page
    author: saeed Ghanavat
 -
  scope:
   path: '_posts'
   type: posts
  values:
   layout: post
   author: Saeed Ghanavat
  authors:
   saeedg:
     name: Saeed Ghanavat
     email: codingmarvels@ghanavat.co.uk
     url: https://codingmarvels.com     

exclude:
  - vendor
