# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coding Marvels
email: codingmarvels@ghanavat.co.uk
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://codingmarvels.com" # the base hostname & protocol for your site, e.g. https://codingmarvels.com
footerEmailTitle: "Contact me:"
#twitter_username: Maybe!
github_username:  ghanavat

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

repository: "codingmarvels_blog"

comments:
  enabled: true
  show_count: true
  receiver: https://codingmarvelscommenting.azurewebsites.net/api/PostComment
  
emptyArray: []

defaults: 
 -
   scope:
    path: ''
    type: pages
   values:
    layout: page
    author: saeedG
 -
  scope:
   path: '_posts'
   type: posts
  values:
   layout: post
   author: saeedG
  authors:
   saeedg:
     name: Saeed Ghanavat
     email: codingmarvels@ghanavat.co.uk
     url: https://codingmarvels.com     

exclude:
  - vendor
